/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormFieldDidChangeValueDetail } from "@sydle/sydle-one-components/dist/types/components/forms/one-form/one-field/one-field.interface";
export namespace Components {
    interface EloExample {
        /**
          * Field configuration. This attribute must be decorated as a @Prop()
         */
        "field": any;
        /**
          * Field value. This attribute must be decorated as a @Prop()
         */
        "value": any;
        /**
          * Path of field value in the reference eObject.
         */
        "valuePath"?: string;
    }
    interface EloMapViewerComponent {
    }
}
export interface EloExampleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEloExampleElement;
}
declare global {
    interface HTMLEloExampleElement extends Components.EloExample, HTMLStencilElement {
    }
    var HTMLEloExampleElement: {
        prototype: HTMLEloExampleElement;
        new (): HTMLEloExampleElement;
    };
    interface HTMLEloMapViewerComponentElement extends Components.EloMapViewerComponent, HTMLStencilElement {
    }
    var HTMLEloMapViewerComponentElement: {
        prototype: HTMLEloMapViewerComponentElement;
        new (): HTMLEloMapViewerComponentElement;
    };
    interface HTMLElementTagNameMap {
        "elo-example": HTMLEloExampleElement;
        "elo-map-viewer-component": HTMLEloMapViewerComponentElement;
    }
}
declare namespace LocalJSX {
    interface EloExample {
        /**
          * Field configuration. This attribute must be decorated as a @Prop()
         */
        "field"?: any;
        /**
          * Event emited when the field changes its value.
         */
        "onSyOneFormFieldDidChangeValue"?: (event: EloExampleCustomEvent<FormFieldDidChangeValueDetail>) => void;
        /**
          * Field value. This attribute must be decorated as a @Prop()
         */
        "value"?: any;
        /**
          * Path of field value in the reference eObject.
         */
        "valuePath"?: string;
    }
    interface EloMapViewerComponent {
    }
    interface IntrinsicElements {
        "elo-example": EloExample;
        "elo-map-viewer-component": EloMapViewerComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "elo-example": LocalJSX.EloExample & JSXBase.HTMLAttributes<HTMLEloExampleElement>;
            "elo-map-viewer-component": LocalJSX.EloMapViewerComponent & JSXBase.HTMLAttributes<HTMLEloMapViewerComponentElement>;
        }
    }
}
